version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default
  app:
    build: .
    command: bash -c "sh entrypoint.sh && rails server -b 0.0.0.0"
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - .env
      - .credential
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - default
volumes:
  mysql-data:
    driver: local
